security:
    
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        
    providers:
        in_memory:
            memory: 
                users:
                    admin:
                        password: 12345
                        roles: 'ROLE_ADMIN'
    firewalls:
        
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:     
            pattern : ^/
            anonymous: true
            provider: in_memory
            form_login:
                check_path: loginCheck
                login_path: login
            logout:
                path: loginOut
                target: /
                
        admin:
            pattern: ^/admin
            anonymous: false
            provider: in_memory
            # le formulaire de login pour que symfony sache où il campe
            form_login:
                check_path: loginCheck
                login_path: login
            logout:
                path: loginOut
                target: /
                
    encoders:
        Symfony\Component\Security\Core\User\User:  plaintext
        AppBundle\Entity\User:
            algorithm: plaintext
            ignore_case: false     
   