security:
    
        
    providers:
        in_memory:
            memory: 
                users:
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'
            
    firewalls:
        
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:     
            pattern : ^/
            anonymous: true
            provider: in_memory
            form_login:
                check_path: loginCheck
                login_path: login
                default_target_path: /login
            logout:
                path: loginOut
                target: /login
       
    
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entity\User:
            algorithm: plaintext
            ignore_case: false       
            
    access_control:   
        # Un admin ou un user classique peut ajouter une annonce ... quelque chose d'étrange est ici ....
        - { path: ^/admin, roles: [ROLE_ADMIN , ROLE_USER] }       
             
            